### ISSUE TITLE
empty output transforming BW png files

### ISSUE THREAD

**Issue by alicanb** [fiji/register_virtual_stack_slices#4]
I'm trying to transform a stack of BW png files, but the output images are all black. If I first convert to tiff, then transform, it works.

**Comment by alicanb** [comment]
I think it is not an issue directly related to this program, it is due to the intensity level of the 'whites' in my image, the outputs are probably not "all black" but have pixels with very low but nonzero intensity. I will probably delete this issue after I do couple tests.

**Comment by alicanb** [comment]
Yep, its as I thought. I'm closing the issue.

**Comment by iarganda** [comment]
Perfect!
