### ISSUE TITLE
What's the meaning of data in *.XML

### ISSUE THREAD

**Issue by FengZhiheng** [fiji/register_virtual_stack_slices#8]
![image](https://user-images.githubusercontent.com/27288257/67860437-cb6b2000-fb58-11e9-8e64-33d3d945bb00.png)

What's the meaning of data value in XML files. I am gong to wrap image in Matlab. But I don't understand the var(data, RigidModel2D, TranslationModel2D and so on) in xml.
I am very appreciate your help. Sorry for my poor English.

**Comment by iarganda** [comment]
Hello @FengZhiheng ,

Sorry for the late answer. The information contained in the XML refers to the transforms applied to the image and their values. In your case, there is a rigid transform (rotation and translation) and a 2D transform as well. You might want to have a look at the mpicbg.trakem2.transform API: https://javadoc.scijava.org/Fiji/mpicbg/trakem2/transform/package-summary.html

I hope this helps!
